spring:
  application:
    name: truelayer-service
  config:
    import: "optional:configserver:http://configserver:8071/"
  output:
    ansi:
      enabled: always
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: redis
      port: 6379
      database: 0
      password: password
      timeout: 60000
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        updateAccountKafka-out-0:
          destination: truelayer-account-update-topic
          contentType: application/json
        updateAccountBalanceKafka-out-0:
          destination: truelayer-account-balance-update-topic
          contentType: application/json
        requestAccountBalanceFromTruelayer-in-0:
          destination: request-account-balance-update-topic
          group: ${spring.application.name}
          contentType: application/json

truelayer:
  client-id:
  client-secret:
  authorization-grant-type: authorization_code
  redirect-uri: http://localhost:8080/api/v1/bank/callback
  auth-base-uri: https://auth.truelayer-sandbox.com
  data-base-uri: https://api.truelayer-sandbox.com
  client-name: TrueLayer

feign:
  client:
    config:
      default:
        loggerLevel: full

server:
  port: 8084
  servlet:
    context-path: /

logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  application:
    name: ${spring.application.name}
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0