spring:
  application:
    name: isa-service
  config:
    import: "optional:configserver:http://configserver:8071/"
  output:
    ansi:
      enabled: always
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      function:
        definition: addIsaAccount
      bindings:
        addIsaAccount-in-0:
          destination: new-isa-account-topic
          group: ${spring.application.name}
        addIsaBalance-in-0:
          destination: new-balance-topic
          group: ${spring.application.name}



feign:
  client:
    config:
      default:
        loggerLevel: full

server:
  port: 8083
  servlet:
    context-path: /

logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  application:
    name: ${spring.application.name}
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
